### ISSUE TITLE
Typescript definition files seems to be wrong

### ISSUE THREAD

**Issue by sbatezat** [n1ru4l/graphql-live-query#798] opened 2021-11-11 11:51 UTC
>node -v
v16.13.0
>npm -v
8.1.0

Both of applyLiveQueryJSONDiffPatchGenerator.d.ts & liveQueryJSONDiffPatchGenerator.d.ts are referencing : import("../../graphql-live-query/src") and it's causing compilation issue on my side (using tsc).
When I manually patch them to import("../graphql-live-query") everything is working fine.
I've also changed import("../../graphql-live-query-patch/src/ExecutionPatchResult") to import("../graphql-live-query-patch/ExecutionPatchResult") in liveQueryJSONDiffPatchGenerator.d.ts.

Is there something wrong on my side?

**Comment by n1ru4l** [comment] 2021-11-13 13:57
Are you using the latest version of the packages? Could you share a reproduction on code sandbox or as a GitHub repository?

**Comment by n1ru4l** [comment] 2022-01-02 08:51
Gonna close this due to missing feedback.

**Closed by n1ru4l** 2022-01-02 08:51 UTC
